name: Pokedex Health Check

on:
  schedule:
    - cron: '30 13 * * 2'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed URL
        uses: Jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-9v5d.onrender.com/
          max-attempts: 3
          retry-delay: 5s
