name: Deployment pipeline

env:
  PUSH: ${{ github.event_name == 'push' }}
  SKIP: ${{ contains(join(github.event.commits.*.message, ' '), '#skip') }}
  NO_PLAYWRIGHT: ${{ contains(join(github.event.commits.*.message, ' '), '#no-e2e') }}

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: jest
        run: npm test
      - name: playwright
        if: ${{ !env.NO_PLAYWRIGHT }}
        run: |
          npx playwright install --with-deps
          npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: debug push event
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "EVENT_NAME: ${{ github.event_name }}"
          echo "PUSH BOOLEAN: ${{ env.PUSH }}"
          echo "PUSH BOOLEAN another way: ${{ github.event_name == 'PUSH' }}"
          echo "SKIP BOOLEAN: ${{ env.SKIP }}"
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "GITHUB_HEAD_REF: ${{ github.head_ref }}"
          echo "GITHUB_BASE_REF: ${{ github.base_ref }}"
          echo "GITHUB_REF_NAME: ${{ github.ref_name }}"
          echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"
          echo "COMMIT_MESSAGES: ${{ join(github.event.commits.*.message, ', ') }}"
      - name: debug pr event
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "EVENT_NAME: ${{ github.event_name }}"
          echo "PUSH BOOLEAN: ${{ env.PUSH }}"
          echo "PUSH BOOLEAN another way: ${{ github.event_name == 'PUSH' }}"
          echo "SKIP BOOLEAN: ${{ env.SKIP }}"
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "GITHUB_HEAD_REF: ${{ github.head_ref }}"
          echo "GITHUB_BASE_REF: ${{ github.base_ref }}"
          echo "GITHUB_REF_NAME: ${{ github.ref_name }}"
          echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"
          echo "PR_TITLE: ${{ github.event.pull_request.title }}"
          echo "PR_BODY: ${{ github.event.pull_request.body }}"
      - name: deploy
        if: ${{ github.event_name == 'PUSH' && !env.SKIP }}
        run: |
          echo "Deploying.."
          curl "https://api.render.com/deploy/srv-${{secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}"
  tag_release:
    if: ${{ github.event_name == 'PUSH' && !github.env.SKIP }}
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: bump version and push tag
        uses: anothrNick/github-tag-action@1.70.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
